### ISSUE TITLE
Publishing Tasks Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-reactive-messaging-rest-integration#26]
Publishing Tasks

- [x] Create `qa` branch from `dev` branch
- [x] Rename `dev` to `master` branch
- [x] Rename the guide repo
   - guide-microprofile-reactive-messaging-rest-integration
- [x] Check that tags and categories are updated
  - https://github.com/OpenLiberty/guides-common/pull/494
- [x] Refresh `qa` staging site and verify 
- [x] If qa site has no problem, request to refresh openliberty.io site
- [x] For `master` branch, add a tag by creating a new release for this repo with name "1st-release"
